version: 2

jobs:
  prepare:
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .npmrc
            - node_modules
            - node
            - module
            - types

  test:
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run lint
      - run: npm run coverage
      - store_artifacts:
          path: coverage

  publish:
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm version ${CIRCLE_TAG}
      - run: npm publish

workflows:
  version: 2
  main:
    jobs:
      - prepare:
          filters:
            tags: { only: /^v\d+\.\d+\.\d+$/ }
      - test:
          requires: [prepare]
          filters:
            tags: { only: /^v\d+\.\d+\.\d+$/ }
      - publish:
          context: authorized
          requires: [prepare]
          filters:
            branches: { ignore: /.*/ }
            tags: { only: /^v\d+\.\d+\.\d+$/ }
